# saved as config.yaml in tokyo-mistakes/exampleSite
# Tokyo-Mistakes Theme Configuration
baseURL: "https://schingon.com"
languageCode: "en-us"
title: "The S Chingon Experience"
theme: "tokyo-mistakes"

# Build settings
buildDrafts: false
buildFuture: false
canonifyURLs: true

# Markup settings
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "tokyo-night"
    lineNos: true
  tableOfContents:
    startLevel: 1
    endLevel: 2
    ordered: false

# Params for theme
params:
  # Site settings
  author: "Gallo Chingon"
  description: "From Army veteran to kink educator - one Texan's journey through life, love, and everything in between."
  imageBase: "/images/"

  # Theme settings
  colorScheme: "auto" # auto, light, dark
  showReadingTime: true
  showToc: true
  tocMaxItems: 12

  # Social sharing (FIXED STRUCTURE)
  socialSharing: true
  shareButtons:
    size: "medium"
    icon: "normal"
    buttonmargin: "0.3em"
  sharePresets:
    text:
      - facebook
      - twitter
      - reddit
      - linkedin
      - email
      - telegram
    media:
      - facebook
      - twitter
      - pinterest
      - whatsapp
      - telegram
      - instagram
  # Comments (Remark42)
  comments:
    enabled: true
    giscus:
      repo: "githubUsername/repoName"
      repoId: "R_kgDOLXYZ12" # Replace with your repo ID
      category: "Announcements"
      categoryId: "DIC_kwDOLXYZ12abc" # Replace with your category ID
      mapping: "pathname"
      reactionsEnabled: "1"
      emitMetadata: "0"
      inputPosition: "bottom"
      lang: "en"
      loading: "lazy"

  # Search
  search:
    enabled: true

# Menu configuration (removed blog per your request)
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 10
    - name: "Podcast"
      url: "/podcast"
      weight: 20
    - name: "Featured"
      url: "/featured"
      weight: 30
    - name: "About"
      url: "/about"
      weight: 40
