# saved as config.yaml in tokyo-mistakes/exampleSite
# Tokyo-Mistakes Theme Configuration (YAML)

baseURL: "https://schingon.com"
languageCode: "en-us"
title: "S Chingon"
theme: "tokyo-mistakes"

# Build settings
buildDrafts: false
buildFuture: false
canonifyURLs: true

taxonomies:
  tag: "tags"
  category: "categories"

# Output formats (enable JSON on home for /index.json)
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS

# Markup settings
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "tokyo-night"
    lineNos: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false

# Params for theme
params:
  # Site settings
  author: "Gallo Chingon"
  description: "From Army veteran to kink educator - one widowed Texan's journey through life, love, and everything in between."
  imageBase: "/images/"

  # Theme modes (group + scheme replaces colorScheme)
  schemeGroup: "color" # neutral | color
  scheme: "auto" # auto | light | dark

  # Reading experience
  showReadingTime: true
  showToc: true
  tocMaxItems: 9

  # Social sharing (fixed structure)
  socialSharing: true
  shareButtons:
    size: "medium"
    icon: "normal"
    buttonmargin: "0.3em"
  sharePresets:
    text:
      - facebook
      - twitter
      - reddit
      - linkedin
      - email
      - telegram
    media:
      - facebook
      - twitter
      - pinterest
      - whatsapp
      - telegram
      - instagram

  # Comments (giscus preferred)
  commentsDefault: true
  comments:
    enabled: true
    giscus:
      repo: "githubUsername/repoName"
      repoId: "R_kgDOLXYZ12" # Replace with your repo ID
      category: "Announcements"
      categoryId: "DIC_kwDOLXYZ12abc" # Replace with your category ID
      mapping: "pathname"
      reactionsEnabled: "1"
      emitMetadata: "0"
      inputPosition: "bottom"
      lang: "en"
      loading: "lazy"

  # Search (LoveIt/Lunr style)
  search:
    enabled: true

  # Media autoplay (global + per-surface)
  autoplay: "off" # off | on (master switch)
  autoplay_list_page: "off" # default off
  autoplay_single_page: "on" # default on (only applies if autoplay == "on")

  # Floating buttons
  backToTopThreshold: 600

# Menu configuration (removed blog per your request)
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 10
    - name: "Podcast"
      url: "/podcast"
      weight: 20
    - name: "Featured"
      url: "/featured"
      weight: 30
    - name: "About"
      url: "/about"
      weight: 40

# Robots and sitemap (SEO)
enableRobotsTXT: true
